# Specify installation directory
cask_args appdir: '/Applications'

# tap 'homebrew/cask-fonts'

brew 'awscli'
brew 'bash'
brew 'curl'
brew 'docker'
brew 'docker-compose'
brew 'foreman'
brew 'fzf'
brew 'gcc'
brew 'git'
brew 'icu4c'
brew 'mise'
brew 'openssl@3'
brew 'ossp-uuid'
brew 'readline'
brew 'wget'
brew 'zlib'
brew 'zoxide'
brew 'zsh-autosuggestions'

cask 'firefox'
cask 'font-hack-nerd-font'
cask 'godot'
cask 'hiddenbar'
cask 'iterm2'
cask 'karabiner-elements'
cask 'notion'
cask 'obsidian'
cask 'postico'
cask 'readdle-spark'
cask 'rectangle'
cask 'slack'
cask 'visual-studio-code'
cask 'warp'
